apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: python-docker-push
  namespace: tekton-pipelines
  labels:
    app: python-backend
    task-type: docker-push
spec:
  description: |
    Python Backend ka Docker image Docker Hub par push karta hai.
    Kaniko use karke image build aur push dono karta hai.
    vanshtyagi1/python-backend image Docker Hub par jayegi.
  workspaces:
    - name: python-source
      description: Python backend source code workspace
  params:
    - name: image-name
      type: string
      description: Docker image ka naam
      default: "vanshtyagi1/python-backend"
    - name: image-tag
      type: string
      description: Docker image ka tag
      default: "latest"
  steps:
    - name: push-python-image
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --context=/workspace/python-source/apps/python-backend
        - --dockerfile=/workspace/python-source/apps/python-backend/Dockerfile
        - --destination=vanshtyagi1/python-backend:$(params.image-tag)
        - --verbosity=info
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
        items:
          - key: .dockerconfigjson
            path: config.json
