apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: python-docker-build
  namespace: tekton-pipelines
  labels:
    app: python-backend
    task-type: docker-build
spec:
  description: |
    Python Backend ka Docker image build karta hai.
    Kaniko use karke image build hoti hai.
    Docker Hub par push nahi karta - sirf build karta hai.
  workspaces:
    - name: python-source
      description: Python backend source code workspace
  params:
    - name: image-name
      type: string
      description: Docker image ka naam
      default: "vanshtyagi1/python-backend"
    - name: image-tag
      type: string
      description: Docker image ka tag
      default: "latest"
  steps:
    - name: build-python-image
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --context=/workspace/python-source/apps/python-backend
        - --dockerfile=/workspace/python-source/apps/python-backend/Dockerfile
        - --no-push
        - --tar-path=/workspace/python-source/python-image.tar
        - --verbosity=info
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
        items:
          - key: .dockerconfigjson
            path: config.json
