server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Angular routing support
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Python backend proxy
    location /python/ {
        proxy_pass http://python-backend-service:8000/;
        proxy_set_header Host $host;
    }

    # Java backend proxy
    location /java/ {
        proxy_pass http://java-backend-service:8080/;
        proxy_set_header Host $host;
    }

    # Logs meaningful banao
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}
