apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: java-backend-pipelinerun
  namespace: tekton-pipelines
  labels:
    app: java-backend
spec:
  pipelineRef:
    name: java-backend-pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: docker-config
      secret:
        secretName: dockerhub-secret
  params:
    - name: repo-url
      value: "https://github.com/Vanshtyagii0/cicd-gitops-project.git"
    - name: image-ref
      value: "vanshtyagi1/java-backend"
    - name: image-tag
      value: "v1.0"
