apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: python-backend-run
  namespace: default
spec:
  pipelineRef:
    name: cicd-pipeline
  params:
  - name: app-name
    value: "python-backend"
  - name: context-path
    value: "/workspace/apps/python-backend"
